#ifndef QFTBX_BOUNDARY_DATA_H
#define QFTBX_BOUNDARY_DATA_H

#include <cstdint>
#include <QVector>

#include "src/core/boundaries/boundary_types.h"
#include <QPointF>
#include <QMap>
#include <QString>

namespace qftbx {

/**
 * @brief View over one boundary computation's results, non-owning by
 * default.
 *
 * The BoundaryEngine keeps its containers as members and hands out views,
 * so destroying such a view never touches them and temporary views can be
 * created and deleted freely. The file parser instead allocates fresh
 * containers with no other owner: it builds its view with
 * takeOwnership(), and then destroying the view deep-deletes everything
 * it holds.
 *
 * Per design frequency, boundaries() maps each specification name (the
 * persisted keys of the .qft files: "Tracking", "Stability", "SensorNoise",
 * "OutputDisturbance", "InputDisturbance", "ControlEffort") to its traced
 * contours, unionBoundaries() holds the
 * 1D union of all specifications and unionBuckets() the same union bucketed
 * by phase, sorted by magnitude.
 */
class BoundaryData
{
public:
    BoundaryData(BoundarySet boundaries, std::vector<bool> openFlags,
                 std::vector<bool> upperFlags, std::int32_t phaseCount, QPointF phaseRange,
                 UnionTraces unionBoundaries, UnionBuckets unionBuckets,
                 std::int32_t magnitudeCount, QPointF magnitudeRange);

    const BoundarySet & boundaries () const;
    std::int32_t phaseCount () const;
    std::int32_t magnitudeCount () const;
    QPointF phaseRange () const;
    QPointF magnitudeRange () const;
    const UnionTraces & unionBoundaries () const;
    const UnionBuckets & unionBuckets () const;
    const std::vector<bool> & openFlags () const;
    const std::vector<bool> & upperFlags () const;

    //There is no takeOwnership() any more, and no copy to forbid. It carried
    //an m_owns flag because the same class was sometimes a VIEW over the
    //engine's containers and sometimes the OWNER of a loaded project's, and
    //the destructor had to be told which. Holding the containers by value
    //answers it: there is one owner, this object, always. The copy and
    //assignment that had to be deleted to stop a double free are now
    //perfectly safe and generated by the compiler.

private:
    BoundarySet m_boundaries;
    std::vector<bool> m_openFlags;
    std::vector<bool> m_upperFlags;
    std::int32_t m_phaseCount = 0;
    QPointF m_phaseRange;
    std::int32_t m_magnitudeCount = 0;
    QPointF m_magnitudeRange;
    UnionTraces m_unionBoundaries;
    UnionBuckets m_unionBuckets;
};

} // namespace qftbx

//Transitional: consumers still refer to the class unqualified.
using qftbx::BoundaryData;

#endif // QFTBX_BOUNDARY_DATA_H
