#ifndef QFTBX_BOUNDARY_DATA_H
#define QFTBX_BOUNDARY_DATA_H

#include <cstdint>
#include "src/core/range.h"
#include <vector>

#include "src/core/boundaries/boundary_types.h"
#include <string>

namespace qftbx {

/**
 * @brief The results of one boundary computation, held by value.
 *
 * Per design frequency, boundaries() maps each specification name (the
 * persisted keys of the .qft files: "Tracking", "Stability", "SensorNoise",
 * "OutputDisturbance", "InputDisturbance", "ControlEffort") to its traced
 * contours, unionBoundaries() holds the
 * 1D union of all specifications and unionBuckets() the same union bucketed
 * by phase, sorted by magnitude. openFlags() and upperFlags() say, per
 * frequency, whether that union is open and whether its allowed side is
 * above it.
 */
class BoundaryData
{
public:
    BoundaryData(BoundarySet boundaries, std::vector<bool> openFlags,
                 std::vector<bool> upperFlags, std::int32_t phaseCount, qftbx::Range phaseRange,
                 UnionTraces unionBoundaries, UnionBuckets unionBuckets,
                 std::int32_t magnitudeCount, qftbx::Range magnitudeRange);

    const BoundarySet & boundaries () const;
    std::int32_t phaseCount () const;
    std::int32_t magnitudeCount () const;
    qftbx::Range phaseRange () const;
    qftbx::Range magnitudeRange () const;
    const UnionTraces & unionBoundaries () const;
    const UnionBuckets & unionBuckets () const;
    const std::vector<bool> & openFlags () const;
    const std::vector<bool> & upperFlags () const;

    //There is no takeOwnership() any more, and no copy to forbid. It carried
    //an m_owns flag because the same class was sometimes a VIEW over the
    //engine's containers and sometimes the OWNER of a loaded project's, and
    //the destructor had to be told which. Holding the containers by value
    //answers it: there is one owner, this object, always. The copy and
    //assignment that had to be deleted to stop a double free are now
    //perfectly safe and generated by the compiler.

private:
    BoundarySet m_boundaries;
    std::vector<bool> m_openFlags;
    std::vector<bool> m_upperFlags;
    std::int32_t m_phaseCount = 0;
    qftbx::Range m_phaseRange;
    std::int32_t m_magnitudeCount = 0;
    qftbx::Range m_magnitudeRange;
    UnionTraces m_unionBoundaries;
    UnionBuckets m_unionBuckets;
};

} // namespace qftbx


#endif // QFTBX_BOUNDARY_DATA_H
